### ISSUE TITLE
Add archisw and dataflows type

### ISSUE THREAD

**Issue by yalgva** [tomolimo/impacts#1]
Hello

Is it possible to add connection type to these objects ?

I installed plugins but I don't see them in the list

Thanks for your great job Olivier !!!

**Comment by tomolimo** [comment]
Hello,
What do you mean by archisw? And by dataflows type?
Could you give more details?
Thank you,
Regards,
Tomolimo

**Comment by yalgva** [comment]
there are two plugins with objects, and I would like to add connection between these objects and server or computers

**Comment by tomolimo** [comment]
ok, I understand now
This is very easy, but you need to update the DB directly
What is the object type you would like to add?

**Comment by tomolimo** [comment]
just to give an example: here is my own config: ["PluginAppliancesAppliance","PluginSimcardSimcard","PluginAccountsAccount","Printer","SoftwareLicense","Software","NetworkEquipment","Monitor","Computer","Peripheral","Phone"]

in the table glpi_plugin_impacts_configs table

**Comment by tomolimo** [comment]
juste replace PluginAppliancesAppliance by the object type name

**Comment by tomolimo** [comment]
And add in the impacts/pics folder a PNG picture that will have the name of the object type (like impacts/pics/PluginAppliancesAppliance.png)

**Comment by tomolimo** [comment]
Could it be that you want to list impacts between PluginArchiswSwcomponent and other objects?
Then use the following configuration (json array):
["PluginArchiswSwcomponent","Computer"]
And add a PNG: idea copy/paste the impacts/pics/PluginAppliancesAppliance.png file and rename it impacts/pics/PluginArchiswSwcomponent.png

**Comment by yalgva** [comment]
Hello Olivier,

Can I add other plugins or the number is limited ?

**Comment by yalgva** [comment]
I tried your solution but nothing appears in the list

![image](https://user-images.githubusercontent.com/30655170/53717292-fb421680-3e57-11e9-99bd-52e62e9d8931.png)

**Comment by tomolimo** [comment]
Hello @yalgva 
1. There is no limit for the list of types (you may add as many plugin types as you want).
1. The manually added plugins will not appear in the type list form (and if you changed the list in the DB, then beware to not click on the "save" button in the form, otherwise you may lost the plugins that do not appear).

regards,
Tomolimo

**Comment by yalgva** [comment]
Thank you so much

Have a nice week !
