### ISSUE TITLE
Impact analysis and people notification

### ISSUE THREAD

**Issue by ggfgwillie** [tomolimo/impacts#13]
Hi Tomolimo,

I am a new user in GLPI and in the impact plugin developed by you.

I am interested in hierarchically representing applications, including responsible people and users.
With the above information, when I am going to make a change to my infrastructure, I would be interested notify people about the eventual unavailability based on the information entered in the impact plugin.
Is there a way to obtain people list from the plugin?
If not, do you know if this functionality is available in any other plugin, or do you eventually find it feasible to develop it?

regards
Guillermo

**Comment by tomolimo** [comment]
Hello @ggfgwillie 

Which GLPI version do you use?
Could you detail the way you would like to get this list?
Could you detail the criterion you would like to use to trigger notification?

Thank you
Regards,

Tomolimo

**Comment by ggfgwillie** [comment]
Good morning Tomolimo,
Below I explain:

The installed versions are:
GLPI see 9.4.6
plugin "Asset impacts" (impacts) v1.3.5
Plugin "Apps structures" (archisw) v2.1.4
Additionnal fields (fields) v1.10.3
Objects management plugin (genericobject) ver 2.8.0
Databases plugin (databases) v2.2.1
Web applications plugin (webapplications) v2.6.0

As I mentioned before, the objective of this improvement is to notify the responsible people and users of a system when a maintenance task will be performed. The notification could be done automatically by GLPI via email, or manually outside the GPLI (using a email client). The automatic option is more complex because it requires obtaining the user list (email), write the message to send, and send the email, on the other hand, the manual option only nedd the list of users to be notified (name, surname, email, telephone, etc) in a exportable format such as CSV.

You culd find the information of the users in two different places:
a) user and group fields on asset (fiels defined by GPLI, or fields defined by a plugin such "aditional fields",  "functional area", "apps structures
![contactos computadora](https://user-images.githubusercontent.com/67067776/85437301-c3854380-b560-11ea-8a89-eabd5c57f7cb.png)
![contactos objetcts management](https://user-images.githubusercontent.com/67067776/85437337-d0a23280-b560-11ea-8bf0-ede9e08ec948.png)
![contactos web applications](https://user-images.githubusercontent.com/67067776/85437341-d13ac900-b560-11ea-8524-81f532220ad2.png)
![contactos app structure +++](https://user-images.githubusercontent.com/67067776/85437345-d1d35f80-b560-11ea-9353-fb0213b50e39.png)
![contactos databases](https://user-images.githubusercontent.com/67067776/85437348-d1d35f80-b560-11ea-9f10-28ba0a297923.png)
![usuario](https://user-images.githubusercontent.com/67067776/85437359-d566e680-b560-11ea-86c9-5dfd6511486c.png)
![grupo](https://user-images.githubusercontent.com/67067776/85437360-d5ff7d00-b560-11ea-951a-6273e13cb244.png)
![impacto1](https://user-images.githubusercontent.com/67067776/85437369-d9930400-b560-11ea-9bda-5f3be4290a52.png)
![impacto2](https://user-images.githubusercontent.com/67067776/85437370-d9930400-b560-11ea-97c3-e088fc79117d.png)








", or others).
b) User and group information linked through the impact plugin.
(See attached images for both cases)
In both cases, the needed information are user fields. For groups, it's necesary to first obtain the list of asociated users.

The way to execute this functionality would be by positioning myself in the asset that will be unavailable, and when pressing a button the system will go through all the linked assets through the impact plugin and will generate the list of users described in a) and b).
Depending on the possibilities of the development, a CSV would be generated or the email would be sent automatically.

Thanks for your time.
regards
William

**Comment by tomolimo** [comment]
Will not be solved as the feature has been integrated in to GLPI core tables
See: https://github.com/tomolimo/impacts/releases/tag/2.0.3
