### ISSUE TITLE
Impact short names

### ISSUE THREAD

**Issue by zamach132** [tomolimo/impacts#14]
Name's in inpact diagram are shorter (only 10 digits). 
Is it possible change it for full names of assets ?

Version 1.3.5
GLPI 1.4.5

**Comment by tomolimo** [comment]
Hello @zamach132 
Could you show a screencopy of what you explained?
Thank you
Regards,
Tomolimo

**Comment by zamach132** [comment]
![Bez tytułu](https://user-images.githubusercontent.com/62652551/90504887-07a45700-e152-11ea-94c7-8e5e8d847be8.jpg)

**Comment by tomolimo** [comment]
Will not be solved as the feature has been integrated in to GLPI core tables
See: https://github.com/tomolimo/impacts/releases/tag/2.0.3
