### ISSUE TITLE
Fatal error: Cannot redeclare printValue() (previously declared in ...

### ISSUE THREAD

**Issue by jairockman** [tomolimo/impacts#15]
Hi,

I did the upgrade of the plugin to 1.3.6 to solve the conflict with Tag Management Plugin in 1.3.5, but now I got another error, in the "List of assets impacted by" section. 

Look screenshot:

![image](https://user-images.githubusercontent.com/56606032/91101591-0d57dc00-e62d-11ea-89ae-7638f5560792.png)

And the drawing pane (Impact graph) disapear. The "List of assets impacting" section is OK.

**Comment by tomolimo** [comment]
Hello @jcervantes-sipecom 
Is it again a conflict with the Tag plugin?
Could you try again with a disabled Tag plugin?
Thank you,
Regards,
Tomolimo

**Comment by jairockman** [comment]
Hi @tomolimo ,

No it's not a conflict with Tag plugin, I already have it disable, but the error is the same like the before picture attached.

> Fatal error: Cannot redeclare printValue() (previously declared in /var/www/html/glpi/plugins/impacts/inc/config.class.php:136) in /var/www/html/glpi/plugins/impacts/inc/config.class.php on line 136

**Comment by tomolimo** [comment]
See https://github.com/tomolimo/impacts/releases/tag/1.3.7
