### ISSUE TITLE
Migration to GLPI 9.5 Core Impact Analysis

### ISSUE THREAD

**Issue by jairockman** [tomolimo/impacts#16]
Hi @tomolimo, I wanted to know if there is any plugin migration plan for GLPI 9.4.X to 9.5.X because the new version of GLPI brings Impacts in the Core of it. But, in order not to reconfigure everything again what had already been configured in the plugin, is there a way to migrate the plugin relationships to the core of GLPI 9.5.x?

**Comment by tomolimo** [comment]
Hello @jcervantes-sipecom 

Currently there is no plan, but I'm going to investigate the possibilities to create one.
So stay tuned.

Regards,
Tomolimo

**Comment by jairockman** [comment]
Thank you so much @tomolimo.

**Comment by pbfoliveira** [comment]
@tomolimo I sent you a pull request. We did a test at work and the plugin worked normally after updating to GLPI 9.5. All the information already registered worked perfectly.

**Comment by tomolimo** [comment]
Fixed by https://github.com/tomolimo/impacts/releases/tag/2.0.3
