### ISSUE TITLE
Add a Database into the list of enabled types for impact analysis

### ISSUE THREAD

**Issue by JoseAntonio29** [tomolimo/impacts#20]
Hi,

I'm trying to add a Database into the list of enabled types for impact analysis. I have already added the object "PluginDatabaseDatabase" via the dropdown "Impact Itemtypes". However, the object has not appeared on the list and I can't include the item in an impact analysis. What could be the problem? I'm using GLPI v9.5.5.

Thanks.

**Comment by tomolimo** [comment]
Hello @JoseAntonio29 
Could you provide more information about your GLPI configuration?
Thank you
Regards,
Tomolimo

**Comment by JoseAntonio29** [comment]
Hello,
I have installed GLPI v9.5.5, Mariadb 10.5.10, Apache 2.4.6 and PHP 7.2 on a CentOS-7 machine. I have installed the latest version of the plugin. Do you need any specific information?
Thanks for your help.
José Antonio.

**Comment by tomolimo** [comment]
Hello @JoseAntonio29 
Could you provide the info you can find in Setup > General menu, System tab?
And screen copies of the issue?
Thank you
Regards,
Tomolimo

**Comment by JoseAntonio29** [comment]
This is my configuration

GLPI 9.5.5 (/glpi => /var/www/html/glpi)
Installation mode: TARBALL

Server
 
Operating system: Linux tecpi_prueba.cica.es 3.10.0-1160.31.1.el7.x86_64 #1 SMP Thu Jun 10 13:32:12 UTC 2021 x86_64
PHP 7.2.34 apache2handler (Core, PDO, PDO_ODBC, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bcmath,
	bz2, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml,
	mbstring, mysqli, mysqlnd, odbc, openssl, pcre, pdo_mysql, pdo_sqlite, posix, session, shmop, soap, sockets, sodium, sqlite3,
	standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.6 (CentOS) PHP/7.2.34 ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
Server Software: MariaDB Server
	Server Version: 10.5.11-MariaDB
	Server SQL Mode: 
	Parameters: root@localhost/GLPICTP
	Host info: Localhost via UNIX socket
	
PHP version is at least 7.2.0 - Perfect!PHP version is at least 7.2.0 - Perfect!
Sessions support is available - Perfect!Sessions support is available - Perfect!
Allocated memory > 64 Mio - Perfect!Allocated memory > 64 Mio - Perfect!
mysqli extension is installedmysqli extension is installed
ctype extension is installedctype extension is installed
fileinfo extension is installedfileinfo extension is installed
json extension is installedjson extension is installed
mbstring extension is installedmbstring extension is installed
iconv extension is installediconv extension is installed
zlib extension is installedzlib extension is installed
curl extension is installedcurl extension is installed
gd extension is installedgd extension is installed
simplexml extension is installedsimplexml extension is installed
intl extension is installedintl extension is installed
ldap extension is installedldap extension is installed
apcu extension is installedapcu extension is installed
Zend OPcache extension is installedZend OPcache extension is installed
xmlrpc extension is installedxmlrpc extension is installed
CAS extension is installedCAS extension is installed
exif extension is installedexif extension is installed
zip extension is installedzip extension is installed
bz2 extension is installedbz2 extension is installed
sodium extension is installedsodium extension is installed
Database version seems correct (10.5.11) - Perfect!Database version seems correct (10.5.11) - Perfect!
Timezones seems loaded in databaseTimezones seems loaded in database
The log file has been created successfully.The log file has been created successfully.
Write access to /var/www/html/glpi/files/_cache has been validated.Write access to /var/www/html/glpi/files/_cache has been validated.
Write access to /var/www/html/glpi/config has been validated.Write access to /var/www/html/glpi/config has been validated.
Write access to /var/www/html/glpi/files/_cron has been validated.Write access to /var/www/html/glpi/files/_cron has been validated.
Write access to /var/www/html/glpi/files has been validated.Write access to /var/www/html/glpi/files has been validated.
Write access to /var/www/html/glpi/files/_dumps has been validated.Write access to /var/www/html/glpi/files/_dumps has been validated.
Write access to /var/www/html/glpi/files/_graphs has been validated.Write access to /var/www/html/glpi/files/_graphs has been validated.
Write access to /var/www/html/glpi/files/_lock has been validated.Write access to /var/www/html/glpi/files/_lock has been validated.
Write access to /var/www/html/glpi/files/_pictures has been validated.Write access to /var/www/html/glpi/files/_pictures has been validated.
Write access to /var/www/html/glpi/files/_plugins has been validated.Write access to /var/www/html/glpi/files/_plugins has been validated.
Write access to /var/www/html/glpi/files/_rss has been validated.Write access to /var/www/html/glpi/files/_rss has been validated.
Write access to /var/www/html/glpi/files/_sessions has been validated.Write access to /var/www/html/glpi/files/_sessions has been validated.
Write access to /var/www/html/glpi/files/_tmp has been validated.Write access to /var/www/html/glpi/files/_tmp has been validated.
Write access to /var/www/html/glpi/files/_uploads has been validated.Write access to /var/www/html/glpi/files/_uploads has been validated.
Write access to /var/www/html/glpi/marketplace has been validated.Write access to /var/www/html/glpi/marketplace has been validated.
Web access to files directory is protectedWeb access to files directory is protected
SELinux configuration is OK.SELinux configuration is OK.

GLPI constants
 
GLPI_ROOT: /var/www/html/glpi
GLPI_CONFIG_DIR: /var/www/html/glpi/config
GLPI_VAR_DIR: /var/www/html/glpi/files
GLPI_MARKETPLACE_DIR: /var/www/html/glpi/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_FORCE_EMPTY_SQL_MODE: 1
GLPI_DOC_DIR: /var/www/html/glpi/files
GLPI_CACHE_DIR: /var/www/html/glpi/files/_cache
GLPI_CRON_DIR: /var/www/html/glpi/files/_cron
GLPI_DUMP_DIR: /var/www/html/glpi/files/_dumps
GLPI_GRAPH_DIR: /var/www/html/glpi/files/_graphs
GLPI_LOCAL_I18N_DIR: /var/www/html/glpi/files/_locales
GLPI_LOCK_DIR: /var/www/html/glpi/files/_lock
GLPI_LOG_DIR: /var/www/html/glpi/files/_log
GLPI_PICTURE_DIR: /var/www/html/glpi/files/_pictures
GLPI_PLUGIN_DOC_DIR: /var/www/html/glpi/files/_plugins
GLPI_RSS_DIR: /var/www/html/glpi/files/_rss
GLPI_SESSION_DIR: /var/www/html/glpi/files/_sessions
GLPI_TMP_DIR: /var/www/html/glpi/files/_tmp
GLPI_UPLOAD_DIR: /var/www/html/glpi/files/_uploads
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /var/www/html/glpi/locales
GLPI_VERSION: 9.5.5
GLPI_SCHEMA_VERSION: 9.5.5
GLPI_MIN_PHP: 7.2.0
GLPI_YEAR: 2021

Libraries
 
htmlawed/htmlawed version 1.2.5 in (/var/www/html/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.1.6 in (/var/www/html/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.6 in (/var/www/html/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.3.5 in (/var/www/html/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/html/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/html/glpi/vendor/sabre/http/lib)
sabre/uri in (/var/www/html/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib)
laminas/laminas-cache in (/var/www/html/glpi/vendor/laminas/laminas-cache/src)
laminas/laminas-i18n in (/var/www/html/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-serializer in (/var/www/html/glpi/vendor/laminas/laminas-serializer/src)
monolog/monolog in (/var/www/html/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/html/glpi/vendor/sebastian/diff/src)
elvanto/litemoji in (/var/www/html/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/html/glpi/vendor/symfony/console)
scssphp/scssphp in (/var/www/html/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/html/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/html/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/html/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/html/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/html/glpi/vendor/ramsey/uuid/src)
psr/log in (/var/www/html/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/html/glpi/vendor/psr/simple-cache/src)
mexitek/phpcolors in (/var/www/html/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/html/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/html/glpi/vendor/guzzlehttp/psr7/src)
wapmorgan/unified-archive in (/var/www/html/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/html/glpi/vendor/paragonie/sodium_compat/src)
phpCas version 1.3.9 in (/usr/share/pear)

SQL replicas
 
Not active

Notifications
 
Way of sending emails: PHP

Mails receivers
 

Plugins list
 
	actualtime           Name: ActualTime                     Version: 1.5.0      State: Enabled
	webapplications      Name: Aplicativos web                Version: 3.0.0      State: Enabled
	archisw              Name: Apps structures                Version: 2.2.5      State: Enabled
	impacts              Name: Asset impacts                  Version: 2.0.3      State: Enabled
	databases            Name: Bases de datos                 Version: 2.3.2      State: Enabled
	cmdb                 Name: CMDB                           Version: 2.2.1      State: Enabled
	connections          Name: Connections                    Version: 9.5        State: Enabled
	accounts             Name: Cuentas                        Version: 2.6.0      State: Enabled
	datainjection        Name: Data injection                 Version: 2.9.0      State: Enabled
	archimap             Name: Diagrams                       Version: 3.1.0      State: Enabled
	addressing           Name: Direccionamiento IP            Version: 2.9.0      State: Enabled
	formcreator          Name: Form Creator                   Version: 2.11.4     State: Enabled
	archifun             Name: Functional Areas               Version: 2.2.2      State: Not installed
	fusioninventory      Name: FusionInventory                Version: 9.5+3.0    State: Enabled
	geninventorynumber   Name: geninventorynumber             Version: 2.5.0      State: Not installed
	genericobject        Name: Gestión de objetos             Version: 2.11.0     State: Enabled
	order                Name: Gestión de Pedidos             Version: 2.7.0      State: Enabled
	pdf                  Name: Impresión a pdf                Version: 2.0.0      State: Enabled
	reports              Name: Informes                       Version: 1.14.1     State: Enabled
	livechat             Name: Livechat                       Version: 1.0.4      State: Enabled
	shellcommands        Name: Órdenes de consola             Version: 3.0.0      State: Enabled
	protocolsmanager     Name: Protocols manager              Version: 1.4.2      State: Enabled
	resources            Name: Recursos humanos               Version: 2.7.0      State: Enabled
	dashboard            Name: Tablero de informes            Version: 1.0.2      State: Enabled
	vip                  Name: VIP                            Version: 1.7.2      State: Enabled

Besides, I have installed "Databases" plugin and via the dropdown "Impact Itemstypes" I have add the object as shown in the image. However, when I create an impact analysis, I can't see the database object in the enabled types to include a databsde object in my analysis.  
![error](https://user-images.githubusercontent.com/36765834/125422156-2ffcf048-7c38-4ec6-9d40-f27d5aa1b151.PNG)

Thanks for your help.

**Comment by tomolimo** [comment]
Hello @JoseAntonio29 

You've added a new impact itemtype: that's perfect (apart the fact that you have forgotten the icon extension -> .png), but have you added 'Database' in the list of assets that are managed by the impact analysis?
![image](https://user-images.githubusercontent.com/7569958/125428011-281a0be7-99cd-4fb5-b105-fa46a1326fad.png)

Thank you,
Regards,
Tomolimo

**Comment by tomolimo** [comment]
also see https://github.com/tomolimo/impacts/releases/tag/2.0.4

**Comment by JoseAntonio29** [comment]
That works perfect. I have forgotten to add "Database" in the list of assets (and also the .png). 
Thanks for your help!
José Antonio.

**Comment by tomolimo** [comment]
You're welcome,
Regards,
Tomolimo
