### ISSUE TITLE
Cannot create an impact analysis for an App Structure

### ISSUE THREAD

**Issue by JoseAntonio29** [tomolimo/impacts#22]
Hello,
I have installed archisw plugin and I would like to create an impact analysis for the apps structures that this plugin provides. I have installed the assests impacts plugin and included the following configuration.

![Captura 2](https://user-images.githubusercontent.com/36765834/126156607-b6c62f4b-4e96-4d46-98dd-b7aca447ba82.PNG)
![Captura 3](https://user-images.githubusercontent.com/36765834/126156612-046f256c-d74d-475d-939c-96e709698c47.PNG)

However, when I cannot see the Impact analysis tab when I go in Assests > App Structures as can be seen in the following picture.

![Captura 1 ](https://user-images.githubusercontent.com/36765834/126156972-e355aa98-2810-4fd7-8789-01ff1a0594e2.PNG)

Any suggestions?

Thanks in advance for your help.

**Comment by FedericoFelliny** [comment]
Same thing. But you can add app structures items to impact analysis of other elements

**Comment by FedericoFelliny** [comment]
I did it!!!
@JoseAntonio29, if it is still relevant, then you need to add a line to /plugins/archisw/inc/swcomponent.php

`$this->addStandardTab('Impact', $ong, $options);`  to line 291

![image](https://user-images.githubusercontent.com/92057291/136281906-41adc345-5207-4dcf-9831-fd5c73c93043.png)
