### ISSUE TITLE
Cannot config

### ISSUE THREAD

**Issue by grego1981** [tomolimo/impacts#3]
Good morning,

I have installed the plugin and tried to go to config page, but enabling debug I get the error below, I believe it refers to the old SimCard management plugin which I uninstalled since some time before. 

Asset impact setup |  
-- | --
Asset list | Fatal error: Uncaught Error: Class 'PluginSimcardSimcard' not found in /var/www/html/glpi/plugins/impacts/inc/config.class.php:171 Stack trace: #0 /var/www/html/glpi/plugins/impacts/inc/config.class.php(116): PluginImpactsConfig::getAssetList(true) #1 /var/www/html/glpi/plugins/impacts/inc/config.class.php(157): PluginImpactsConfig::showConfigForm(Object(Config)) #2 /var/www/html/glpi/inc/commonglpi.class.php(485): PluginImpactsConfig::displayTabContentForItem(Object(Config), '1', '') #3 /var/www/html/glpi/ajax/common.tabs.php(92): CommonGLPI::displayStandardTab(Object(Config), 'PluginImpactsCo...', '', Array) #4 {main} thrown in /var/www/html/glpi/plugins/impacts/inc/config.class.php on line 171

**Comment by tomolimo** [comment]
Hello
Yes currently if a plugin is no longer available and has been used in the possible asset impact list, then it is not deleted from the list. And of course the plugin is still trying to get the name of the class of the plugin.
The solution is to change manually the config in the glpi_plugin_impacts_configs table. 
Thank you 
Regards 
Tomolimo

**Comment by grego1981** [comment]
Hello! I have used the patched files from #2  and it works fine.

Thank you!
