### ISSUE TITLE
how to associate supplier to appliance

### ISSUE THREAD

**Issue by yalgva** [tomolimo/impacts#5]
Hello Tomolimo,

I would like to add the supplier of the appliance, is it possible ?

Thank you for your help

**Comment by tomolimo** [comment]
Hello @yalgva,
What do you mean?
Could you detail a little bit?
May be give an example or a screenshot?
Thank you,
Regards,
Tomolimo

**Comment by yalgva** [comment]
![image](https://user-images.githubusercontent.com/30655170/62109404-87902280-b2ac-11e9-89f8-4ae6708ed961.png)

**Comment by tomolimo** [comment]
Thank you,
I understand now :)
Which version of the plugin do you use? In which version of GLPI?

**Comment by yalgva** [comment]
1.3.1 and glpi 9.4.2

Do you know inforapid knowledgebase builder ? it is a software to make a map
I try do use impact to include all connection with an appliance : 

computer, server, appliance, supplier, knowledgebase.
For our service desk it is very useful to have a view of dependencies starting from appliance

**Comment by yalgva** [comment]
we could also associate a service (department) to impacted items, what do you think about it ?

**Comment by tomolimo** [comment]
> inforapid knowledgebase builder

I don't know this software.

But if you use impacts 1.3.1, there is no difficulties to add Suppliers in the list of assets:

1. Go to impact configuration to add the class "Supplier" into the managed asset list:
![image](https://user-images.githubusercontent.com/7569958/62109907-8c090b00-b2ad-11e9-9db6-316857c90724.png)

1. add a picture: you may copy/paste PluginAccountsAccount.png into Supplier.png
![image](https://user-images.githubusercontent.com/7569958/62110056-db4f3b80-b2ad-11e9-9edf-4a5ffeb9b254.png)

1. then add a supplier in the impact list of an appliance:
![image](https://user-images.githubusercontent.com/7569958/62110150-15204200-b2ae-11e9-9de6-993476c7e2d5.png)

**Comment by yalgva** [comment]
many services...

**Comment by yalgva** [comment]
excellent !!!!!!

**Comment by tomolimo** [comment]
> we could also associate a service (department) to impacted items, what do you think about it ?

How do you define service (or department) in GLPI?
Do you use a group for that?

**Comment by yalgva** [comment]
yes, and it works perfectly, thank you so much !!!
