### ISSUE TITLE
Feature : different color according to input / output

### ISSUE THREAD

**Issue by yalgva** [tomolimo/impacts#6]
Hello Tomolimo,

Is it possible to improve the view ?

change the color according to input / output : input blue / output green

Is it possible to improve the basic view with more structure with domain (actualy a circle with all around the goal)

Appliance 
             Configuration Item
                               Supplier

Thank you for your answer

**Comment by tomolimo** [comment]
Hello @yalgva 
Could you provide detailed specifications of what is expected?
Thank you,
Regards,
Tomolimo

**Comment by yalgva** [comment]
The idea is to diffenciate input of output
![Capture](https://user-images.githubusercontent.com/30655170/62442772-39ba6500-b759-11e9-9356-40ebcfbf42fd.PNG)

**Comment by tomolimo** [comment]
Hello @yalgva 
Ok I understand, but what is the criterion to decide if a link is an input or an output?
As far as I understand, an input is also always an output?
Thank you,
Regards,
Tomolimo

**Comment by yalgva** [comment]
input impacts application 
output impacts  from application

**Comment by yalgva** [comment]
and the must would be other color like green material to material / db

**Comment by tomolimo** [comment]
Hello @yalgva 
I'm going to investigate to know what is possible to do.
And I'll keep you informed,
Regards,
Tomolimo

**Comment by yalgva** [comment]
Thank you so much, have a nice day

**Comment by tomolimo** [comment]
The impact feature is integrated into the GLPI core
And it has this requested feature of the coloring

See: https://github.com/tomolimo/impacts/releases/tag/2.0.3
