### ISSUE TITLE
Class '' not found

### ISSUE THREAD

**Issue by AHinMaine** [tomolimo/impacts#7]
I'm getting the following error in my apache httpd log:

```Class '' not found in /var/www/html/glpi-9.4.3/plugins/impacts/front/impact.form.php on line 37, referer: https://xxxx.xxxx/glpi/front/computer.form.php?id=96```

(Just in case that's not clear, it's the word Class followed by two single quotes.)

I'm running GLPI 9.4.3.  Running on a CentOS 7.6 server with php 5.6.35.

I installed Impacts 1.3.1 (fetched from the Releases section here on github) and, just to test it, went into "Asset impact setup" and added to the asset list "Computers (Computer)" and "Printers (Printer)".  Then I went into a Computer object, clicked into the Impacts tab, then clicked the Add button.  At that point I get an HTTP 500 error and the log shows what I pasted above.

Here's what's in my db:

```
mysql> SELECT * FROM glpi_development.glpi_plugin_impacts_configs;
+----+------------------------+------------+
| id | assets                 | db_version |
+----+------------------------+------------+
|  1 | ["Computer","Printer"] | 1.0.0      |
+----+------------------------+------------+
1 row in set (0.00 sec)

mysql> SELECT * FROM glpi_development.glpi_plugin_impacts_impacts;
Empty set (0.00 sec)
```

Any other information I can provide that would be helpful?

**Comment by tomolimo** [comment]
Hello @AHinMaine 
I'm going to try to reproduce this, and I'll keep you informed about it.
Thank you
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello @AHinMaine 
I made a test with following configuration:
GLPI 9.4.3
PHP 5.6.40
And with an empty database (newly created)
And I created a printer and a computer in assets,
And I have been able to add an impact between the computer and the printer without any troubles...

Could you try to get the network traces? To do this in your browser, press F12 to open the developer tools, and then if you redo the test, you should be able to find a network trace. In this trace you should be able to find the POST to the impact.form.php page, and you should be able to find the parameters sent to the page. Could you copy/paste them in this issue?

Thank you,
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Just one question: before pressing on the Add button, did you select an item type and an item?
Like following:
![image](https://user-images.githubusercontent.com/7569958/62710438-98047380-b9f7-11e9-8f17-6687fdb89295.png)

**Comment by AHinMaine** [comment]
The POST looks like this:

itemtype_1: 
items_id_1: 0
add: Add
itemtype_2: Computer
items_id_2: 96
_glpi_csrf_token: 92522fcf2ea411522af3e19ecf93851c


I also do not have the option to select an item type.  It just looks like this:

![image](https://user-images.githubusercontent.com/239004/62720382-e99d0600-b9d7-11e9-944b-aff69075fa2c.png)

**Comment by tomolimo** [comment]
Then you have a problem at form creation, and not at form submit.
Let me check this tomorrow
Regards
Tomolimo

**Comment by AHinMaine** [comment]
I think I see it.

It's this bit here:  https://github.com/tomolimo/impacts/blob/master/inc/impact.class.php#L501-L502

In profiles, I disable everything under the Assistance tab as I don't want or need the GLPI ticketing system.  Since this plugin is tied to the Assistance "See hardware of my groups" flag, it couldn't proceed with the getAssetList() and everything else.

**Comment by tomolimo** [comment]
Hello @AHinMaine 
Thank you for your analysis!
I really don't see why I set this filter: probably a copy/paste that was too big 😢!
I'm going to fix this right now,
Thank you
Regards,
Tomolimo
