### ISSUE TITLE
PHP Warning(2): strcmp() expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by yalgva** [tomolimo/impacts#8]
Hello Tomolimo,

This message appears every seconds in php error logs, thank you for your help

[2019-09-02 10:42:43] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in C:\inetpub\wwwroot\inc\toolbox.class.php line 659
  *** PHP Warning(2): strcmp() expects parameter 1 to be string, array given
  Backtrace :
  :                                                  
  plugins\impacts\inc\config.class.php:141           strcmp()
  plugins\impacts\inc\impact.class.php:508           PluginImpactsConfig::getAssetList()
  plugins\impacts\inc\impact.class.php:389           PluginImpactsImpact::dropdownAllDevices()
  plugins\impacts\inc\impact.class.php:156           PluginImpactsImpact::showOppositeListForItem()
  plugins\impacts\inc\impact.class.php:137           PluginImpactsImpact::showForItem()
  inc\commonglpi.class.php:485                       PluginImpactsImpact::displayTabContentForItem()
  ajax\common.tabs.php:92                            CommonGLPI::displayStandardTab()
  {"user":"2430@GLPI02","mem_usage":"0.000\", 2.89Mio)"} 
[2019-09-02 10:42:43] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in C:\inetpub\wwwroot\inc\toolbox.class.php line 659
  *** PHP Warning(2): strcmp() expects parameter 1 to be string, array given
  Backtrace :
  :                                                  
  plugins\impacts\inc\config.class.php:141           strcmp()
  plugins\impacts\inc\impact.class.php:508           PluginImpactsConfig::getAssetList()
  plugins\impacts\inc\impact.class.php:389           PluginImpactsImpact::dropdownAllDevices()
  plugins\impacts\inc\impact.class.php:156           PluginImpactsImpact::showOppositeListForItem()
  plugins\impacts\inc\impact.class.php:137           PluginImpactsImpact::showForItem()
  inc\commonglpi.class.php:485                       PluginImpactsImpact::displayTabContentForItem()
  ajax\common.tabs.php:92                            CommonGLPI::displayStandardTab()
  {"user":"2430@GLPI02","mem_usage":"0.000\", 2.89Mio)"} 
[2019-09-02 10:42:43] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in C:\inetpub\wwwroot\inc\toolbox.class.php line 659
  *** PHP Warning(2): strcmp() expects parameter 1 to be string, array given
  Backtrace :
  :                                                  
  plugins\impacts\inc\config.class.php:141           strcmp()
  plugins\impacts\inc\impact.class.php:508           PluginImpactsConfig::getAssetList()
  plugins\impacts\inc\impact.class.php:389           PluginImpactsImpact::dropdownAllDevices()
  plugins\impacts\inc\impact.class.php:156           PluginImpactsImpact::showOppositeListForItem()
  plugins\impacts\inc\impact.class.php:137           PluginImpactsImpact::showForItem()
  inc\commonglpi.class.php:485                       PluginImpactsImpact::displayTabContentForItem()
  ajax\common.tabs.php:92                            CommonGLPI::displayStandardTab()
  {"user":"2430@GLPI02","mem_usage":"0.000\", 2.89Mio)"} 
[2019-09-02 10:42:43] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in C:\inetpub\wwwroot\inc\toolbox.class.php line 659
  *** PHP Warning(2): strcmp() expects parameter 1 to be string, array given
  Backtrace :

**Comment by tomolimo** [comment]
Hello @yalgva 
Coud you give GLPI version, and plugin version?
Thank you
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello @yalgva 
And I also need to have the list of installed plugins.
Thank you
Regards,
Tomolimo

**Comment by yalgva** [comment]
Hello Tomolimo,

glpi 9.4.3
	addressing           Name: Adressage IP                   Version: 2.8.0      State: Enabled
	news                 Name: Alertes                        Version: 1.5.4      State: Enabled
	appliances           Name: Applicatifs                    Version: 2.5.0      State: Enabled
	webapplications      Name: Applications Web               Version: 2.6.0      State: Enabled
	impacts              Name: Asset impacts                  Version: 1.3.2      State: Enabled
	databases            Name: Bases de données               Version: 2.2.1      State: Enabled
	fields               Name: Champs supplémentaires         Version: 1.9.2      State: Enabled
	shellcommands        Name: Commandes Shell                Version: 2.3.0      State: Enabled
	behaviors            Name: Comportements                  Version: 2.2.1      State: Enabled
	uninstall            Name: Cycle de vie des matériels (un Version: 2.6.0      State: Enabled
	mydashboard          Name: Dashboard                      Version: 1.7.4      State: Enabled
	escalade             Name: Escalades                      Version: 2.4.4      State: Enabled
	dataflows            Name: Flux de données                Version: 2.1.0      State: Enabled
	formcreator          Name: Form Creator                   Version: 2.8.4      State: Enabled
	fusioninventory      Name: FusionInventory                Version: 9.4+1.1    State: Enabled
	genericobject        Name: Gestion d'objets               Version: 2.7.0      State: Enabled
	tag                  Name: Gestion des tags               Version: 2.4.2      State: Enabled
	manufacturersimports Name: Imports fabricants             Version: 2.1.2      State: Enabled
	pdf                  Name: Impression pdf                 Version: 1.6.0      State: Enabled
	datainjection        Name: Injection de fichiers          Version: 2.7.0      State: Enabled
	tasklists            Name: Liste des tâches               Version: 1.5.0      State: Enabled
	moreticket           Name: More ticket                    Version: 1.5.0      State: Enabled
	notifications        Name: Notifications                  Version: 9.4+1.0    State: Enabled
	reports              Name: Rapports                       Version: 1.13.1     State: Enabled
	reservation          Name: Reservation                    Version: 2.1.2      State: Enabled
	archisw              Name: Structures d'Applications      Version: 2.1.3      State: Enabled
	dashboard            Name: Tableau de bord                Version: 0.9.7      State: Enabled

**Comment by tomolimo** [comment]
Hello @yalgva 
Could you disable all the plugins (except impacts) and re-enable them till the issue is reproduced?
This will give us the plugin name which is not compatible with impacts, and such I'll be able to fix impacts.
Thank you,
Regards,
Tomolimo

**Comment by yalgva** [comment]
Hello Olivier,
I will do it tomorrow morning and I come back to you
Thx

**Comment by jairockman** [comment]
Hi, I got the same error in differents pages:

- Home>Setup>General>Asset impact setup
- Home>Assets>Computers/Monitors/Phone/ etc

> PHP Warning: strcmp() expects parameter 1 to be string, array given in /var/www/html/glpi/plugins/impacts/inc/config.class.php at line 141
PHP Warning: strcmp() expects parameter 1 to be string, array given in /var/www/html/glpi/plugins/impacts/inc/config.class.php at line 141
PHP Warning: strcmp() expects parameter 1 to be string, array given in /var/www/html/glpi/plugins/impacts/inc/config.class.php at line 141
PHP Warning: strcmp() expects parameter 1 to be string, array given in /var/www/html/glpi/plugins/impacts/inc/config.class.php at line 141
PHP Warning: strcmp() expects parameter 1 to be string, array given in /var/www/html/glpi/plugins/impacts/inc/config.class.php at line 141
PHP Warning: strcmp() expects parameter 1 to be string, array given in /var/www/html/glpi/plugins/impacts/inc/config.class.php at line 141
PHP Warning: strcmp() expects parameter 1 to be string, array given in /var/www/html/glpi/plugins/impacts/inc/config.class.php at line 141

The plugin version is: 1.3.5 and the GLPI version is 9.4.6

I did what you suggest:
>  disable all the plugins (except impacts) and re-enable them

And found the conflict is with **Tag Management (tag) plugin**

**Comment by tomolimo** [comment]
Hello @jcervantes-sipecom 
Which version of the Tag Management plugin do you have?
Thank you,
Regards,
Tomolimo
